"""Comparable transaction selection and deterministic precedent valuation."""

from ma_precedent_transactions.precedent.fixtures import (
    build_precedent_fixture_inputs,
    precedent_fixture_inputs,
)
from ma_precedent_transactions.precedent.models import (
    CalculationInput,
    CalculationStatus,
    CalculationTrace,
    ComparableTransactionDecision,
    ComparableTransactionSet,
    CriterionAssessment,
    CriterionMode,
    CriterionOutcome,
    ImpliedValuationCase,
    ImpliedValuationRange,
    ManualOverride,
    MinorityTreatment,
    MultipleSetKey,
    OverrideAction,
    PeerStatistics,
    PrecedentSelectionPolicy,
    PrecedentValuationOutput,
    SelectionDecision,
    TargetCapitalProfile,
    TargetComparabilityProfile,
    TargetValuationProfile,
    TransactionMultipleResult,
    TransactionMultipleSet,
    ValuationExplanation,
)
from ma_precedent_transactions.precedent.multiples import (
    DEFINITIONS,
    TransactionMultipleEngine,
    TransactionMultiplePolicy,
)
from ma_precedent_transactions.precedent.reasoning import (
    EXPLANATION_INSTRUCTIONS,
    EXPLANATION_SCHEMA,
    LangChainValuationExplanationProvider,
)
from ma_precedent_transactions.precedent.selection import (
    ComparableTransactionSelector,
    DeterministicFixtureComparabilityProvider,
    SoftComparabilityProvider,
)
from ma_precedent_transactions.precedent.service import PrecedentAnalysisService
from ma_precedent_transactions.precedent.valuation import (
    FixtureValuationExplanationProvider,
    PrecedentValuationEngine,
    PrecedentValuationPolicy,
    ValuationExplanationProvider,
)

__all__ = [
    "DEFINITIONS",
    "CalculationInput",
    "CalculationStatus",
    "CalculationTrace",
    "ComparableTransactionDecision",
    "ComparableTransactionSelector",
    "ComparableTransactionSet",
    "CriterionAssessment",
    "CriterionMode",
    "CriterionOutcome",
    "DeterministicFixtureComparabilityProvider",
    "FixtureValuationExplanationProvider",
    "ImpliedValuationCase",
    "ImpliedValuationRange",
    "LangChainValuationExplanationProvider",
    "ManualOverride",
    "MinorityTreatment",
    "MultipleSetKey",
    "OverrideAction",
    "PeerStatistics",
    "PrecedentAnalysisService",
    "PrecedentSelectionPolicy",
    "PrecedentValuationEngine",
    "PrecedentValuationOutput",
    "PrecedentValuationPolicy",
    "SelectionDecision",
    "SoftComparabilityProvider",
    "TargetCapitalProfile",
    "TargetComparabilityProfile",
    "TargetValuationProfile",
    "TransactionMultipleEngine",
    "TransactionMultiplePolicy",
    "TransactionMultipleResult",
    "TransactionMultipleSet",
    "ValuationExplanation",
    "ValuationExplanationProvider",
    "EXPLANATION_INSTRUCTIONS",
    "EXPLANATION_SCHEMA",
    "precedent_fixture_inputs",
    "build_precedent_fixture_inputs",
]
