"""Small fictitious M0 fixture set shared by tests and later milestones."""

from __future__ import annotations

from datetime import UTC, date, datetime
from decimal import Decimal

from ma_due_diligence.domain import (
    AdjustmentDirection,
    AdjustmentType,
    AnalystDecision,
    BalanceSheetItem,
    BalanceSheetItemType,
    Confidentiality,
    ConflictStatus,
    DealImpactArea,
    DealType,
    DiligenceEngagement,
    DiligenceFact,
    DiligenceFinding,
    DiligenceFixtureSet,
    DiligenceScope,
    DiligenceWorkstream,
    DocumentType,
    EntityReference,
    EvidenceReference,
    EvidenceSourceType,
    ExtractionMethod,
    FactConflict,
    FactValue,
    FinancialAdjustment,
    FinancialPeriod,
    FindingStatus,
    FindingType,
    FollowUpQuestion,
    HumanReviewAction,
    InclusionTreatment,
    LikelihoodBand,
    MaterialityAssessment,
    MissingInformation,
    MissingInformationStatus,
    Money,
    ParseStatus,
    PeriodKind,
    Priority,
    ProposalStatus,
    ProvenanceChain,
    QualitativeMateriality,
    QuestionStatus,
    Recurrence,
    ReviewActionType,
    ReviewStatus,
    RiskAssessment,
    Severity,
    StateField,
    SupportStatus,
    TransactionContext,
    VdrDocument,
)


def build_synthetic_fixture() -> DiligenceFixtureSet:
    """Return an offline case covering the ten M0 fixture scenarios."""

    engagement_id = "eng-northstar-001"
    target = EntityReference("entity-northstar", "Northstar Components Ltd", jurisdiction="GB")
    buyer = EntityReference("entity-river", "River Peak Holdings plc", jurisdiction="GB")
    fy2025 = FinancialPeriod(
        PeriodKind.FISCAL_YEAR,
        "FY2025",
        date(2025, 1, 1),
        date(2025, 12, 31),
    )
    engagement = DiligenceEngagement(
        engagement_id=engagement_id,
        target=target,
        buyer=buyer,
        transaction=TransactionContext(DealType.ACQUISITION, "Proposed acquisition of Northstar"),
        scope=DiligenceScope(
            (
                DiligenceWorkstream.FINANCIAL,
                DiligenceWorkstream.COMMERCIAL,
                DiligenceWorkstream.LEGAL_CONTRACTUAL,
                DiligenceWorkstream.OPERATIONAL,
            )
        ),
        as_of_date=date(2026, 2, 15),
        reporting_currency="GBP",
        jurisdiction="England and Wales",
        materiality_assumptions=("Amounts are presented in GBP millions",),
        review_status=ReviewStatus.IN_PROGRESS,
    )
    retrieved = datetime(2026, 2, 10, 12, 0, tzinfo=UTC)
    documents = (
        VdrDocument(
            "doc-audited-fs",
            engagement_id,
            "Northstar_FY2025_Audited.pdf",
            DocumentType.FINANCIAL_STATEMENTS,
            (DiligenceWorkstream.FINANCIAL,),
            "vdr://1.01",
            "FY2025 Audited Financial Statements",
            target,
            fy2025,
            "final",
            retrieved,
            Confidentiality.CONFIDENTIAL,
            ParseStatus.PARSED,
        ),
        VdrDocument(
            "doc-management-presentation",
            engagement_id,
            "Northstar_Management_Presentation.pdf",
            DocumentType.MANAGEMENT_PRESENTATION,
            (DiligenceWorkstream.FINANCIAL, DiligenceWorkstream.COMMERCIAL),
            "vdr://2.01",
            retrieved_at=retrieved,
            confidentiality=Confidentiality.CONFIDENTIAL,
            parse_status=ParseStatus.PARSED,
        ),
        VdrDocument(
            "doc-sales-report",
            engagement_id,
            "Northstar_Customer_Sales_FY2025.xlsx",
            DocumentType.SALES_REPORT,
            (DiligenceWorkstream.COMMERCIAL,),
            "vdr://3.04",
            period=fy2025,
            retrieved_at=retrieved,
            confidentiality=Confidentiality.HIGHLY_CONFIDENTIAL,
            parse_status=ParseStatus.PARSED,
        ),
        VdrDocument(
            "doc-customer-contract",
            engagement_id,
            "Apex_Customer_Agreement.pdf",
            DocumentType.CUSTOMER_CONTRACT,
            (DiligenceWorkstream.LEGAL_CONTRACTUAL, DiligenceWorkstream.COMMERCIAL),
            "vdr://4.02",
            retrieved_at=retrieved,
            confidentiality=Confidentiality.HIGHLY_CONFIDENTIAL,
            parse_status=ParseStatus.PARSED,
        ),
        VdrDocument(
            "doc-management-accounts",
            engagement_id,
            "Northstar_December_Management_Accounts.xlsx",
            DocumentType.MANAGEMENT_ACCOUNTS,
            (DiligenceWorkstream.FINANCIAL, DiligenceWorkstream.OPERATIONAL),
            "vdr://1.03",
            period=fy2025,
            retrieved_at=retrieved,
            confidentiality=Confidentiality.CONFIDENTIAL,
            parse_status=ParseStatus.PARSED,
        ),
    )
    evidence = (
        EvidenceReference(
            "ev-audited-revenue",
            EvidenceSourceType.VDR_DOCUMENT,
            "doc-audited-fs",
            page_numbers=(42,),
            section="Revenue note",
            table="Segment revenue",
            row="Total revenue",
            source_text="Revenue for FY2025 was GBP 95.0 million.",
            period=fy2025,
        ),
        EvidenceReference(
            "ev-management-revenue",
            EvidenceSourceType.VDR_DOCUMENT,
            "doc-management-presentation",
            page_numbers=(18,),
            section="Financial highlights",
            source_text="FY2025 Revenue: GBP 100.0m",
            period=fy2025,
        ),
        EvidenceReference(
            "ev-addback",
            EvidenceSourceType.VDR_DOCUMENT,
            "doc-management-presentation",
            page_numbers=(22,),
            section="Adjusted EBITDA",
            source_text="Proposed legal fee add-back: GBP 1.2m",
            period=fy2025,
        ),
        EvidenceReference(
            "ev-customer-concentration",
            EvidenceSourceType.VDR_DOCUMENT,
            "doc-sales-report",
            page_numbers=(1,),
            table="Customer revenue",
            row="Apex Retail Group",
            source_text="Apex Retail Group represents 42% of FY2025 revenue.",
            period=fy2025,
        ),
        EvidenceReference(
            "ev-change-control",
            EvidenceSourceType.VDR_DOCUMENT,
            "doc-customer-contract",
            page_numbers=(31,),
            section="Change of Control",
            source_text="Customer may terminate upon a change of control of Supplier.",
        ),
        EvidenceReference(
            "ev-balance-sheet",
            EvidenceSourceType.VDR_DOCUMENT,
            "doc-management-accounts",
            page_numbers=(3,),
            table="Balance sheet",
            source_text="Accrued transaction bonus GBP 3.0m; net working capital GBP 8.0m.",
            period=fy2025,
        ),
    )
    facts = (
        DiligenceFact(
            "fact-revenue-audited",
            engagement_id,
            target,
            "FY2025 revenue",
            FactValue(
                "GBP 95.0 million", numeric_value=Decimal("95.0"), unit="million", currency="GBP"
            ),
            SupportStatus.SINGLE_SOURCE,
            ExtractionMethod.MANUAL,
            (evidence[0],),
            fy2025,
        ),
        DiligenceFact(
            "fact-revenue-management",
            engagement_id,
            target,
            "FY2025 revenue",
            FactValue("GBP 100.0m", numeric_value=Decimal("100.0"), unit="million", currency="GBP"),
            SupportStatus.CONFLICTING,
            ExtractionMethod.AI_ASSISTED,
            (evidence[1],),
            fy2025,
        ),
        DiligenceFact(
            "fact-addback",
            engagement_id,
            target,
            "Proposed EBITDA legal fee add-back",
            FactValue("GBP 1.2m", numeric_value=Decimal("1.2"), unit="million", currency="GBP"),
            SupportStatus.SINGLE_SOURCE,
            ExtractionMethod.AI_ASSISTED,
            (evidence[2],),
            fy2025,
        ),
        DiligenceFact(
            "fact-customer-concentration",
            engagement_id,
            target,
            "Largest customer concentration",
            FactValue("42%", numeric_value=Decimal("42"), unit="percent"),
            SupportStatus.SOURCE_BACKED,
            ExtractionMethod.DETERMINISTIC,
            (evidence[3],),
            fy2025,
        ),
        DiligenceFact(
            "fact-change-control",
            engagement_id,
            target,
            "Apex contract change-of-control clause",
            FactValue(
                "Termination right on change of control", normalized_text="termination_right"
            ),
            SupportStatus.SOURCE_BACKED,
            ExtractionMethod.MANUAL,
            (evidence[4],),
        ),
        DiligenceFact(
            "fact-debt-schedule",
            engagement_id,
            target,
            "Debt schedule",
            None,
            SupportStatus.MISSING,
            ExtractionMethod.MANUAL,
        ),
    )
    concentration_risk = RiskAssessment(
        "Customer concentration",
        LikelihoodBand.HIGH,
        (DealImpactArea.DEAL_THESIS, DealImpactArea.VALUATION),
        "Loss or repricing of the largest customer would materially affect revenue.",
        "Seek retention protections and validate renewal probability.",
    )
    findings = (
        DiligenceFinding(
            "finding-concentration",
            engagement_id,
            DiligenceWorkstream.COMMERCIAL,
            "Customer concentration",
            "Largest customer represents 42% of FY2025 revenue.",
            "Revenue is highly concentrated in Apex Retail Group.",
            FindingType.RISK,
            Severity.HIGH,
            MaterialityAssessment(
                QualitativeMateriality.HIGH,
                percentage=Decimal("42"),
                benchmark="FY2025 revenue",
                rationale="A single customer contributes more than two fifths of revenue.",
            ),
            SupportStatus.SOURCE_BACKED,
            FindingStatus.UNDER_REVIEW,
            "Customer concentration",
            ("fact-customer-concentration",),
            evidence=(evidence[3],),
            impact_areas=(DealImpactArea.DEAL_THESIS, DealImpactArea.VALUATION),
            potential_deal_impact="May affect valuation and transaction protections.",
            recommended_follow_up="Request renewal history and account-level retention evidence.",
            risk=concentration_risk,
            analyst_review_status=ReviewStatus.AWAITING_REVIEW,
        ),
        DiligenceFinding(
            "finding-change-control",
            engagement_id,
            DiligenceWorkstream.LEGAL_CONTRACTUAL,
            "Change of control",
            "Key customer termination right",
            "Apex may terminate its agreement following a change of control.",
            FindingType.RED_FLAG,
            Severity.HIGH,
            MaterialityAssessment(
                QualitativeMateriality.HIGH,
                rationale="Clause affects the target's largest customer relationship.",
            ),
            SupportStatus.SOURCE_BACKED,
            supporting_fact_ids=("fact-change-control",),
            evidence=(evidence[4],),
            impact_areas=(DealImpactArea.CLOSING_CONDITION, DealImpactArea.LEGAL_PROTECTIONS),
            recommended_follow_up="Confirm whether consent is required before closing.",
        ),
    )
    conflicts = (
        FactConflict(
            "conflict-revenue-fy2025",
            engagement_id,
            "FY2025 revenue",
            ("fact-revenue-audited", "fact-revenue-management"),
            ConflictStatus.OPEN,
            (evidence[0], evidence[1]),
        ),
    )
    adjustments = (
        FinancialAdjustment(
            "adjustment-legal-fees",
            engagement_id,
            AdjustmentType.NONRECURRING_LEGAL_EXPENSE,
            "EBITDA",
            Money(Decimal("1.2"), "GBP"),
            fy2025,
            AdjustmentDirection.INCREASE,
            Recurrence.UNCERTAIN,
            ProposalStatus.PROPOSED,
            "Management proposes treating legal fees as nonrecurring.",
            (evidence[2],),
            SupportStatus.SINGLE_SOURCE,
            AnalystDecision.PENDING,
            input_fact_ids=("fact-addback",),
        ),
    )
    balance_sheet_items = (
        BalanceSheetItem(
            "item-transaction-bonus",
            engagement_id,
            BalanceSheetItemType.DEBT_LIKE,
            "Accrued transaction bonus",
            Money(Decimal("3.0"), "GBP"),
            date(2025, 12, 31),
            InclusionTreatment.INCLUDE,
            "The obligation is transaction-related and expected to settle after closing.",
            (evidence[5],),
            SupportStatus.SINGLE_SOURCE,
        ),
        BalanceSheetItem(
            "item-working-capital",
            engagement_id,
            BalanceSheetItemType.WORKING_CAPITAL,
            "Reported net working capital",
            Money(Decimal("8.0"), "GBP"),
            date(2025, 12, 31),
            InclusionTreatment.UNASSESSED,
            "Observation retained for later working-capital analysis.",
            (evidence[5],),
            SupportStatus.SINGLE_SOURCE,
        ),
    )
    missing_information = (
        MissingInformation(
            "missing-debt-schedule",
            engagement_id,
            "Complete debt and covenant schedule",
            DiligenceWorkstream.FINANCIAL,
            Priority.URGENT,
            "Required to identify funded debt, covenants, and debt-like obligations.",
            MissingInformationStatus.REQUESTED,
            True,
            "Please provide the current debt schedule and all covenant agreements.",
        ),
    )
    questions = (
        FollowUpQuestion(
            "question-debt-schedule",
            engagement_id,
            DiligenceWorkstream.FINANCIAL,
            "Please provide the current debt schedule and all covenant agreements.",
            Priority.URGENT,
            "The information is required for net debt diligence.",
            QuestionStatus.OPEN,
            requested_document_or_data="Debt schedule and covenant documents",
        ),
    )
    review_actions = (
        HumanReviewAction(
            "review-concentration-001",
            engagement_id,
            "finding",
            "finding-concentration",
            ReviewActionType.APPROVE_FINDING,
            "Analyst One",
            "The sales report supports the concentration calculation.",
            datetime(2026, 2, 16, 9, 30, tzinfo=UTC),
            (StateField("review_status", "awaiting_review"),),
            (StateField("review_status", "reviewed"),),
        ),
    )
    provenance = (
        ProvenanceChain(
            "lineage-concentration",
            engagement_id,
            "finding-concentration",
            None,
            ("fact-customer-concentration",),
            ("ev-customer-concentration",),
            ("doc-sales-report",),
        ),
        ProvenanceChain(
            "lineage-addback",
            engagement_id,
            None,
            "adjustment-legal-fees",
            ("fact-addback",),
            ("ev-addback",),
            ("doc-management-presentation",),
        ),
    )
    return DiligenceFixtureSet(
        engagement,
        documents,
        evidence,
        facts,
        findings,
        conflicts,
        adjustments,
        balance_sheet_items,
        missing_information,
        questions,
        review_actions,
        provenance,
    )
